services:
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'
      - '8025:8025'
  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: elephpant
      MYSQL_DATABASE: elephpant
      MYSQL_USER: elephpant
      MYSQL_PASSWORD: elephpant
  elephpant:
    image: serversideup/php:8.4-fpm-nginx
    container_name: elephpant-php
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
      - ~/.composer/docker-cache/:/composer:cached
    environment:
      PHP_OPCACHE_ENABLE: "1"
      AUTORUN_ENABLED: "true"
    depends_on:
      - mysql
      - mailhog
volumes:
  mysql-data:
    driver: "local"
